global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:5000']  # if using Docker service name
      # or 'localhost:5000' if running locally
