name: CI/CD DevOps Monitoring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Node.js image
      run: docker build -t yourdockerhubusername/node-app:latest ./app

    - name: Push Node.js image
      run: docker push yourdockerhubusername/node-app:latest

    - name: Deploy stack
      run: |
        docker compose down
        docker compose up -d
